spring.datasource.url=jdbc:postgresql://dpg-d08ouv1r0fns73dlarj0-a.oregon-postgres.render.com:5432/curriculo_leo
spring.datasource.username=curriculo_leo_user
spring.datasource.password=aON2L0QMxdkiauHGq8aDvMJzjklhf34X
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080
